title: 6th Athletics Data Conference
description: > # this means to ignore newlines until "baseurl:"
  07-09 Oct 2025
baseurl: "/athtech" # the subpath of your site, e.g. /blog
url: "espinr.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: W3C Open Athletics Community Group
  link: "https://www.w3.org/community/opentrack/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include:
  - _2018_pages
  - _2021_pages
  - _2023_pages
  - _2025_pages
  - index.html
  - 404.html
  - css

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?q=%23athtech25

# Build settings
markdown: kramdown
permalink: pretty
